import type { Metadata } from "next";
import "@/styles/index.scss"
import { Navbar } from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className="selection:bg-teal-100 selection:text-teal-900">
        <Navbar />
        {children}
      </body>
    </html>
  )
}




