#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 Checking lint issues before committing 🛁🧽'
echo 'please be patient, this may take a while...'

# Check ESLint Standards
yarn lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Fixing it 🧼🧹';
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged
